# /* ---- ðŸ’« https://github.com/JaKooLit ðŸ’« ---- */  #
# wallust configuration - for wallust version 3.0

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "full"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lch"

palette = "dark16"

# Difference between similar colors, used by the colorspace:
#  1          Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite
# threshold = 11

[templates]
#cava.template = 'colors-cava'
#cava.target = '~/.config/cava/config'

#hypr.template = 'colors-hyprland.conf'
#hypr.target = '~/.config/hypr/wallust/wallust-hyprland.conf'

#rofi.template = 'colors-rofi.rasi'
#rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'

#waybar.template = 'colors-waybar.css'
#waybar.target = '~/.config/waybar/wallust/colors-waybar.css'

#swaync.template = 'colors-swaync.css'
#swaync.target = '~/.config/swaync/wallust/colors-wallust.css'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/kitty-themes/01-Wallust.conf'

neopywal.template = "colors-neopywal.vim"
neopywal.target = "~/.cache/wallust/colors_neopywal.vim"
